/* Moses Benz Auto Care — admin panel.
 * The local fallback is intentionally a hash-only demo gate. It is not a substitute for Supabase Auth.
 * For production, configure Supabase and move authorization/RLS server-side.
 */
const ADMIN_PASSWORD_HASH='3e63b248812b2a9a92c8a8fe1f147f38d57ebb9e6d9685dee219d85f8400f089';

document.addEventListener('DOMContentLoaded',()=>{
 const gate=document.getElementById('admin-gate'),shell=document.getElementById('admin-shell'),form=document.getElementById('gate-form'),err=document.getElementById('gate-error'),logout=document.getElementById('admin-logout');
 if(!gate||!shell||!form)return;
 const KEY='mbac_admin_session_v3', SESSIONS='mbac_admin_active_sessions_v1', SESSION_ID=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
 async function hash(s){const b=new TextEncoder().encode(s);const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}
 function sessions(){try{return JSON.parse(localStorage.getItem(SESSIONS)||'[]')}catch{return[]}}
 function prune(){const cutoff=Date.now()-15*60*1000;const x=sessions().filter(s=>s.id===SESSION_ID||s.lastSeen>cutoff);localStorage.setItem(SESSIONS,JSON.stringify(x));return x}
 function claimSession(){const x=prune().filter(s=>s.id!==SESSION_ID);if(x.length>=2)return false;x.push({id:SESSION_ID,lastSeen:Date.now()});localStorage.setItem(SESSIONS,JSON.stringify(x));return true}
 function releaseSession(){localStorage.setItem(SESSIONS,JSON.stringify(sessions().filter(s=>s.id!==SESSION_ID)));}
 const heartbeat=setInterval(()=>{const x=prune().map(s=>s.id===SESSION_ID?{...s,lastSeen:Date.now()}:s);if(sessionStorage.getItem(KEY)==='yes')localStorage.setItem(SESSIONS,JSON.stringify(x));},30000);
 window.addEventListener('beforeunload',releaseSession);
 function show(){gate.hidden=true;shell.hidden=false;if(logout)logout.hidden=false;renderAll();}
 function hide(){sessionStorage.removeItem(KEY);releaseSession();shell.hidden=true;gate.hidden=false;if(logout)logout.hidden=true;}
 if(sessionStorage.getItem(KEY)==='yes'){if(claimSession())show();else sessionStorage.removeItem(KEY);}
 form.addEventListener('submit',async e=>{e.preventDefault();const value=document.getElementById('gate-password').value;const ok=await hash(value)===ADMIN_PASSWORD_HASH;if(ok){if(!claimSession()){err.hidden=false;err.textContent='Two admin sessions are already active on this device. Sign out one session first.';return;}sessionStorage.setItem(KEY,'yes');err.hidden=true;show();form.reset();}else{err.hidden=false;err.textContent='Incorrect password. Try again.';}});
 logout?.addEventListener('click',hide);
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
 function renderCars(){const list=document.getElementById('admin-car-list'),count=document.getElementById('admin-count'),cars=window.MBStore.getCars();count.textContent=cars.length+(cars.length===1?' car':' cars');if(!cars.length){list.innerHTML='<p class="admin-card-note">No cars yet — add one above.</p>';return;}list.innerHTML=cars.map(c=>`<div class="admin-car-row" data-id="${esc(c.id)}"><img src="${esc(c.image)}" alt="${esc(c.name)}" class="admin-car-thumb"><div class="admin-car-info"><div class="admin-car-title"><strong>${esc(c.name)}</strong><span class="admin-status-pill${c.status==='sold'?' sold':''}">${c.status==='sold'?'Sold':'Available'}</span></div><div class="admin-car-meta">${esc(c.year)} · ${esc(c.specTag)} · ${window.MBStore.formatKm(c.mileageKm)} · ${window.MBStore.formatNGN(c.priceNGN)}</div></div><div class="admin-car-actions"><button class="btn btn-ghost-light toggle-status">${c.status==='sold'?'Mark Available':'Mark Sold'}</button><button class="btn btn-ghost-light delete-car" style="border-color:var(--ignition);color:var(--ignition);">Delete</button></div></div>`).join('');
 list.querySelectorAll('.toggle-status').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('.admin-car-row').dataset.id;const c=window.MBStore.getCars().find(x=>x.id===id);if(c?.status==='sold')window.MBStore.markAvailable(id);else window.MBStore.markSold(id);renderCars();}));
 list.querySelectorAll('.delete-car').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('.admin-car-row').dataset.id;const c=window.MBStore.getCars().find(x=>x.id===id);if(confirm(`Delete "${c?.name||'this car'}"?`)){window.MBStore.deleteCar(id);renderCars();}}));}
 function renderServices(){const list=document.getElementById('admin-service-list');if(!list)return;list.innerHTML=window.MBData.getServices().map((x,i)=>`<div class="admin-item"><div class="admin-item-main"><strong>${esc(x)}</strong><small>Shown in the appointment service selector.</small></div><div class="admin-inline-actions"><button class="btn btn-ghost-light" data-delete-service="${i}">Remove</button></div></div>`).join('');list.querySelectorAll('[data-delete-service]').forEach(b=>b.onclick=()=>{const x=window.MBData.getServices();x.splice(Number(b.dataset.deleteService),1);window.MBData.saveServices(x);renderServices();});}
 function renderDiagnostics(){const list=document.getElementById('admin-diagnostic-list');if(!list)return;list.innerHTML=window.MBData.getDiagnostics().map((d,i)=>`<div class="admin-item"><div class="admin-item-main"><strong>${esc(d.code)} · ${esc(d.name)}</strong><small>${esc(d.description)}</small></div><div class="admin-inline-actions"><button class="btn btn-ghost-light" data-delete-diag="${i}">Remove</button></div></div>`).join('');list.querySelectorAll('[data-delete-diag]').forEach(b=>b.onclick=()=>{const x=window.MBData.getDiagnostics();x.splice(Number(b.dataset.deleteDiag),1);window.MBData.saveDiagnostics(x);renderDiagnostics();});}
 function renderSlots(){const list=document.getElementById('admin-slot-list');if(!list)return;const slots=window.MBData.getSlots().sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));list.innerHTML=slots.slice(0,40).map((s,i)=>`<div class="admin-item"><div class="admin-item-main"><strong>${esc(s.date)} · ${esc(s.time)}</strong><small>${s.booked}/${s.capacity} booked · ${esc(s.status)}</small></div><div class="admin-inline-actions"><button class="btn btn-ghost-light" data-delete-slot="${esc(s.id)}">Remove</button></div></div>`).join('');list.querySelectorAll('[data-delete-slot]').forEach(b=>b.onclick=()=>{window.MBData.saveSlots(window.MBData.getSlots().filter(s=>s.id!==b.dataset.deleteSlot));renderSlots();});}
 function renderAppointments(){const list=document.getElementById('admin-appointment-list');if(!list)return;const a=window.MBData.getAppointments().sort((x,y)=>y.createdAt.localeCompare(x.createdAt));list.innerHTML=a.length?a.map(x=>`<div class="admin-item"><div class="admin-item-main"><strong>${esc(x.name)} · ${esc(x.model)}</strong><small>${esc(x.date)} · ${esc(x.time)} · ${esc(x.service)} · ${esc(x.phone)}</small><small>${esc(x.message)}</small>${x.status==='done'?'<span class="review-required">Review required</span>':''}</div><div class="admin-inline-actions"><select class="appointment-status" data-id="${esc(x.id)}"><option ${x.status==='requested'?'selected':''}>requested</option><option ${x.status==='confirmed'?'selected':''}>confirmed</option><option ${x.status==='in_progress'?'selected':''}>in_progress</option><option ${x.status==='done'?'selected':''}>done</option><option ${x.status==='cancelled'?'selected':''}>cancelled</option></select>${x.status==='done'?`<button class="btn btn-primary send-review" data-id="${esc(x.id)}">Request review</button>`:''}</div></div>`).join(''):'<p class="admin-card-note">No appointment requests yet.</p>';
 list.querySelectorAll('.appointment-status').forEach(sel=>sel.onchange=()=>{window.MBData.updateAppointment(sel.dataset.id,{status:sel.value});renderAppointments();});
 list.querySelectorAll('.send-review').forEach(b=>b.onclick=()=>{const x=window.MBData.getAppointments().find(v=>v.id===b.dataset.id);if(!x)return;window.MBData.updateAppointment(x.id,{reviewRequested:true});const link=`${location.origin}${location.pathname.replace('admin.html','review.html')}?appointment=${encodeURIComponent(x.id)}`;const msg=`Hello ${x.name}, thank you for visiting Moses Benz Auto Care. Please leave your service review here: ${link}`;window.open(`https://wa.me/${String(x.phone).replace(/\D/g,'').replace(/^0/,'234')}?text=${encodeURIComponent(msg)}`,'_blank','noopener');renderAppointments();});}
 function renderAll(){renderCars();renderServices();renderDiagnostics();renderSlots();renderAppointments();}
 document.getElementById('add-car-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);window.MBStore.addCar({name:fd.get('name').trim(),year:Number(fd.get('year')),priceNGN:Number(fd.get('priceNGN')),mileageKm:Number(fd.get('mileageKm')),specTag:fd.get('specTag').trim(),image:fd.get('image').trim(),description:fd.get('description').trim(),status:fd.get('status')});e.currentTarget.reset();renderCars();});
 document.getElementById('add-service-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const x=window.MBData.getServices();const name=String(fd.get('name')).trim();if(name&&!x.includes(name)){x.push(name);window.MBData.saveServices(x);}e.currentTarget.reset();renderServices();});
 document.getElementById('add-diagnostic-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const x=window.MBData.getDiagnostics();const code=String(fd.get('code')).trim()||`D${String(x.length+1).padStart(2,'0')}`;x.push({code,name:String(fd.get('name')).trim(),description:String(fd.get('description')).trim()});window.MBData.saveDiagnostics(x);e.currentTarget.reset();renderDiagnostics();});
 document.getElementById('add-slot-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);window.MBData.addSlot({date:fd.get('date'),time:fd.get('time'),capacity:Number(fd.get('capacity'))||1});e.currentTarget.reset();renderSlots();});
 document.getElementById('btn-export-json')?.addEventListener('click',()=>window.MBStore.exportAsJSON());document.getElementById('btn-export-seed')?.addEventListener('click',()=>window.MBStore.exportAsSeedFile());document.getElementById('btn-reset')?.addEventListener('click',()=>{if(confirm('Reset inventory to the built-in defaults?')){window.MBStore.resetToDefaults();renderCars();}});
 const input=document.getElementById('import-file'),status=document.getElementById('import-status');input?.addEventListener('change',()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{window.MBStore.importFromJSONText(r.result);status.hidden=false;status.textContent='Imported '+window.MBStore.getCars().length+' cars.';renderCars();}catch(e){status.hidden=false;status.textContent='Could not import that JSON file.';}};r.readAsText(f);input.value='';});
});
