/* Moses Benz Auto Care — workshop control centre. */
(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const api=()=>window.MBBackend;
  async function ensure(){
  try{
    const s=JSON.parse(sessionStorage.getItem('mbac_admin_session')||'null');
    if(!s?.username){location.replace('/mbac-control-7x4k9');return false;}
    return true;
  }catch{location.replace('/mbac-control-7x4k9');return false;}
}
  function sectionNav(){const buttons=[...document.querySelectorAll('[data-admin-section]')],sections=[...document.querySelectorAll('.admin-directory-section')];const activate=name=>{buttons.forEach(b=>b.classList.toggle('is-active',b.dataset.adminSection===name));sections.forEach(s=>s.hidden=s.id!==`admin-section-${name}`);history.replaceState(null,'',`#${name}`);};buttons.forEach(b=>b.onclick=()=>activate(b.dataset.adminSection));activate(location.hash.slice(1)||buttons[0]?.dataset.adminSection);}
  async function renderCars(){const list=document.getElementById('admin-car-list'),count=document.getElementById('admin-count');if(!list)return;const cars=window.MBStore.getCars();if(count)count.textContent=`${cars.length} cars`;list.innerHTML=cars.length?cars.map(c=>`<article class="admin-car-row"><img src="${esc(c.image)}" alt="${esc(c.name)}" class="admin-car-thumb"><div class="admin-car-info"><div class="admin-car-title"><strong>${esc(c.name)}</strong><span class="admin-status-pill${c.status==='sold'?' sold':''}">${c.status==='sold'?'Sold':'Available'}</span></div><div class="admin-car-meta">${esc(c.brand||'Mercedes-Benz')} · ${esc(c.year)} · ${esc(c.specTag)} · ${window.MBStore.formatKm(c.mileageKm)} · ${window.MBStore.formatNGN(c.priceNGN)}</div><p>${esc(c.description||'')}</p></div><div class="admin-car-actions"><button class="btn btn-ghost-light edit-car" data-id="${esc(c.id)}">Edit</button><button class="btn btn-ghost-light toggle-status" data-id="${esc(c.id)}">${c.status==='sold'?'Mark Available':'Mark Sold'}</button><button class="btn btn-ghost-light delete-car" data-id="${esc(c.id)}">Delete</button></div><form class="admin-car-edit admin-form" data-edit-form="${esc(c.id)}" hidden><div class="form-row"><label>Brand<select name="brand"><option value="Mercedes-Benz" ${c.brand!=='Other Brand'?'selected':''}>Mercedes-Benz</option><option value="Other Brand" ${c.brand==='Other Brand'?'selected':''}>Other Brand</option></select></label><label>Model<input name="name" value="${esc(c.name)}" required></label><label>Year<input name="year" type="number" value="${esc(c.year)}"></label></div><div class="form-row"><label>Price (₦)<input name="priceNGN" type="number" value="${esc(c.priceNGN)}"></label><label>Mileage (km)<input name="mileageKm" type="number" value="${esc(c.mileageKm)}"></label></div><div class="form-row"><label>Spec tag<input name="specTag" value="${esc(c.specTag)}"></label><label>Status<select name="status"><option value="available" ${c.status==='available'?'selected':''}>Available</option><option value="sold" ${c.status==='sold'?'selected':''}>Sold</option></select></label></div><label>Image URL<input name="image" type="url" value="${esc(c.image)}" required></label><label>Description<textarea name="description" rows="3">${esc(c.description||'')}</textarea></label><div class="admin-car-actions"><button class="btn btn-primary" type="submit">Save changes</button><button class="btn btn-ghost-light cancel-edit" type="button">Cancel</button></div></form></article>`).join(''):'<p class="admin-card-note">No cars yet. Add one or run supabase-inventory-seed.sql.</p>';
    list.querySelectorAll('.edit-car').forEach(b=>b.onclick=()=>{const f=list.querySelector(`[data-edit-form="${CSS.escape(b.dataset.id)}"]`);if(f)f.hidden=!f.hidden;});
    list.querySelectorAll('.cancel-edit').forEach(b=>b.onclick=()=>{b.closest('form').hidden=true;});
    list.querySelectorAll('[data-edit-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const id=form.dataset.editForm,f=new FormData(form),btn=form.querySelector('button[type="submit"]');btn.disabled=true;try{await window.MBStore.updateCar(id,{brand:String(f.get('brand')||'Mercedes-Benz'),name:String(f.get('name')).trim(),year:Number(f.get('year')),priceNGN:Number(f.get('priceNGN')),mileageKm:Number(f.get('mileageKm')),specTag:String(f.get('specTag')).trim(),status:String(f.get('status')),image:String(f.get('image')).trim(),description:String(f.get('description')).trim()});await renderCars();}catch(ex){alert(ex.message);}finally{btn.disabled=false;}});
    list.querySelectorAll('.toggle-status').forEach(b=>b.onclick=async()=>{const c=window.MBStore.getCars().find(x=>x.id===b.dataset.id);if(!c)return;try{await (c.status==='sold'?window.MBStore.markAvailable(b.dataset.id):window.MBStore.markSold(b.dataset.id));await renderCars();}catch(ex){alert(ex.message);}});
    list.querySelectorAll('.delete-car').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this vehicle from the shared inventory?'))return;try{await window.MBStore.deleteCar(b.dataset.id);await renderCars();}catch(ex){alert(ex.message);}});
  }
  async function renderAppointments(){const list=document.getElementById('admin-appointment-list');if(!list)return;const c=adminCreds();let items=[];if(api()?.ready){const r=await api().rpc('admin_appointments_list',{p_username:c.username||'',p_password:c.password||''});if(r.ok&&Array.isArray(r.data))items=r.data.map(x=>({id:x.id,name:x.name,email:x.email,phone:x.phone,model:x.model,year:x.year,service:x.service,registration:x.registration,location:x.location||'',message:x.message,status:x.status,scheduledDate:x.scheduled_date,scheduledTime:x.scheduled_time,createdAt:x.created_at}));}if(!items.length)items=window.MBData.getAppointments().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));list.innerHTML=items.length?items.map(x=>`<article class="admin-item admin-appointment-item"><div class="admin-item-main"><strong>${esc(x.name)} · ${esc(x.model)}</strong><small>${esc(x.email)} · ${esc(x.phone)}</small><small>${esc(x.service||'Appointment Request')}${x.year?` · ${esc(x.year)}`:''}${x.location?` · ${esc(x.location)}`:''}</small><small>${esc(x.message||'')}</small><small>${x.scheduledDate||x.scheduledTime?`Scheduled: ${esc(x.scheduledDate||'')} ${esc(x.scheduledTime||'')}`:'Not scheduled yet'}</small></div><div class="admin-appointment-actions"><select class="appointment-status" data-id="${esc(x.id)}"><option value="requested" ${x.status==='requested'?'selected':''}>Requested</option><option value="confirmed" ${x.status==='confirmed'?'selected':''}>Confirmed</option><option value="in_progress" ${x.status==='in_progress'?'selected':''}>In progress</option><option value="done" ${x.status==='done'?'selected':''}>Done</option><option value="cancelled" ${x.status==='cancelled'?'selected':''}>Cancelled</option></select><button class="btn btn-ghost-light adjust-time" data-id="${esc(x.id)}">Adjust date &amp; time</button><button class="btn btn-ghost-light email-customer" data-id="${esc(x.id)}">Via Email</button><button class="btn btn-ghost-light whatsapp-customer" data-id="${esc(x.id)}">Via WhatsApp</button>${x.status==='done'||x.status==='cancelled'?`<button class="btn btn-ghost-light delete-appointment" data-id="${esc(x.id)}">Delete</button>`:''}</div></article>`).join(''):'<p class="admin-card-note">No appointment requests yet.</p>';
    list.querySelectorAll('.appointment-status').forEach(sel=>sel.onchange=async()=>{const id=sel.dataset.id,val=sel.value;try{if(api()?.ready){const r=await api().rpc('admin_appointment_status',{p_username:c.username||'',p_password:c.password||'',p_id:id,p_status:val});if(!r.ok)throw new Error('Could not update appointment.');}window.MBData.updateAppointment(id,{status:val});await renderAppointments();}catch(ex){alert(ex.message);}});
    list.querySelectorAll('.adjust-time').forEach(b=>b.onclick=()=>openTimeModal(items.find(x=>x.id===b.dataset.id)));
    list.querySelectorAll('.email-customer').forEach(b=>b.onclick=()=>{const a=items.find(v=>v.id===b.dataset.id);if(!a)return;const subject=`Moses Benz Auto Care appointment — ${a.model}`;const body=`Hello ${a.name},\n\nYour appointment with Moses Benz Auto Care is scheduled for ${a.scheduledDate||'[DATE]'} at ${a.scheduledTime||'[TIME]'}.\n\nVehicle: ${a.model}${a.year?` (${a.year})`:''}\nLocation: ${a.location||'[LOCATION]'}\n\nPlease reply if you need assistance.\n\nMoses Benz Auto Care`;window.open(`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(a.email)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,'_blank');});
    list.querySelectorAll('.whatsapp-customer').forEach(b=>b.onclick=()=>{const a=items.find(v=>v.id===b.dataset.id);if(!a)return;const phone=String(a.phone||'').replace(/\D/g,'').replace(/^0/,'234');const msg=`Hello ${a.name},\n\nYour appointment with Moses Benz Auto Care is scheduled for ${a.scheduledDate||'[DATE]'} at ${a.scheduledTime||'[TIME]'}.\n\nVehicle: ${a.model}${a.year?` (${a.year})`:''}\nLocation: ${a.location||'[LOCATION]'}\n\nMoses Benz Auto Care`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank');});
    list.querySelectorAll('.delete-appointment').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this completed/cancelled appointment permanently?'))return;try{if(api()?.ready){const r=await api().rpc('admin_appointment_delete',{p_username:c.username||'',p_password:c.password||'',p_id:b.dataset.id});if(!r.ok)throw new Error('Could not delete appointment.');}window.MBData.deleteAppointment(b.dataset.id).catch(()=>{});await renderAppointments();}catch(ex){alert(ex.message);}});
  }
  function openTimeModal(a){const modal=document.getElementById('appointment-time-modal'),form=document.getElementById('appointment-time-form');if(!modal||!form||!a)return;form.querySelector('[name="id"]').value=a.id;form.date.value=/^\d{{4}}-\d{{2}}-\d{{2}}$/.test(a.scheduledDate||'')?a.scheduledDate:'';form.time.value=a.scheduledTime||'';document.getElementById('appointment-time-status').textContent='';modal.hidden=false;modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
  function bindTimeModal(){const modal=document.getElementById('appointment-time-modal'),form=document.getElementById('appointment-time-form');if(!modal||!form)return;const close=()=>{modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');};modal.querySelectorAll('[data-time-close]').forEach(x=>x.onclick=close);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close();});form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),id=String(fd.get('id')),date=String(fd.get('date')),time=String(fd.get('time')),status=document.getElementById('appointment-time-status'),btn=form.querySelector('button[type="submit"]');btn.disabled=true;status.textContent='Saving…';try{if(api()?.ready){const c=adminCreds();const r=await api().rpc('admin_appointment_schedule',{p_username:c.username||'',p_password:c.password||'',p_id:id,p_date:date,p_time:time});if(!r.ok)throw new Error('Could not save appointment time.');}window.MBData.updateAppointment(id,{scheduledDate:date,scheduledTime:time,status:'confirmed'});status.textContent='Date and time updated.';setTimeout(async()=>{close();await renderAppointments();},500);}catch(ex){status.textContent=ex.message;}finally{btn.disabled=false;}};}
  async function renderBeforeAfter(){const list=document.getElementById('admin-before-after-list');if(!list)return;const items=window.MBData.getBeforeAfter();list.innerHTML=items.length?items.map(x=>{const g=Array.isArray(x.gallery)&&x.gallery.length?x.gallery:[{url:x.before,type:'before'},{url:x.after,type:'after'}];return `<article class="admin-item"><div class="admin-gallery-preview">${g.filter(i=>i&&i.url).map(i=>`<img src="${esc(i.url)}" alt="${esc(i.type||'process')} ${esc(x.title)}">`).join('')}</div><div class="admin-item-main"><strong>${esc(x.title)}</strong><small>${esc(x.description||'')}</small><small>${g.filter(i=>i&&i.url).length} gallery images</small></div><button class="btn btn-ghost-light" data-delete-ba="${esc(x.id)}">Remove</button></article>`}).join(''):'<p class="admin-card-note">No before/after projects added yet.</p>';list.querySelectorAll('[data-delete-ba]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this repair story from the shared website?'))return;try{if(api()?.ready){const r=await api().remove('before_after',`id=eq.${encodeURIComponent(b.dataset.deleteBa)}`);if(!r.ok)throw new Error('Could not remove repair story.');}window.MBData.removeBeforeAfter(b.dataset.deleteBa);renderBeforeAfter();}catch(ex){alert(ex.message);}});}
  async function renderCredentials(){const list=document.getElementById('admin-credential-list');if(!list)return;const items=window.MBData.getCredentials();list.innerHTML=items.length?items.map(x=>`<article class="admin-item"><div class="admin-media-pair credential-preview"><img src="${esc(x.image)}" alt="${esc(x.title)}"></div><div class="admin-item-main"><strong>${esc(x.title)}</strong><small>${esc(x.issuer||'')}${x.year?` · ${esc(x.year)}`:''}</small><small>${esc(x.description||'')}</small></div><button class="btn btn-ghost-light" data-delete-credential="${esc(x.id)}">Remove</button></article>`).join(''):'<p class="admin-card-note">No approvals or certificates added yet.</p>';list.querySelectorAll('[data-delete-credential]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this credential?'))return;try{if(api()?.ready){const r=await api().remove('credentials',`id=eq.${encodeURIComponent(b.dataset.deleteCredential)}`);if(!r.ok)throw new Error('Could not remove credential.');}window.MBData.removeCredential(b.dataset.deleteCredential);renderCredentials();}catch(ex){alert(ex.message);}});}
  function adminCreds(){try{return JSON.parse(sessionStorage.getItem('mbac_admin_session')||'null')||{};}catch{return {};}}
  async function renderBlog(){const list=document.getElementById('admin-blog-list');if(!list||!api()?.ready)return;const c=adminCreds();const r=await api().rpc('admin_blog_list',{p_username:c.username||'',p_password:c.password||''});const items=r?.ok&&Array.isArray(r.data)?r.data:[];list.innerHTML=items.length?items.map(x=>`<article class="admin-item"><div class="admin-item-main"><strong>${esc(x.title)}</strong><small>${esc(x.category)} · ${x.published?'Published':'Draft'}</small><small>${esc(x.excerpt)}</small></div><button class="btn btn-ghost-light delete-blog" data-id="${esc(x.id)}">Delete</button></article>`).join(''):'<p class="admin-card-note">No blog posts yet.</p>';list.querySelectorAll('.delete-blog').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this blog post?'))return;const q=await api().rpc('admin_blog_delete',{p_username:c.username||'',p_password:c.password||'',p_id:b.dataset.id});if(!q.ok)alert('Could not delete blog post.');else renderBlog();});}
  async function refreshBlogAdmin(){await renderBlog();await renderBlogComments();}
  function bindBlog(){const form=document.getElementById('add-blog-form');if(!form||form.dataset.bound)return;form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(form),title=String(f.get('title')).trim(),category=String(f.get('category')).trim(),excerpt=String(f.get('excerpt')).trim(),content=String(f.get('content')).trim(),image_url=String(f.get('image_url')||'').trim(),slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36),c=adminCreds(),status=document.getElementById('blog-admin-status');try{const r=await api().rpc('admin_blog_create',{p_username:c.username||'',p_password:c.password||'',p_slug:slug,p_title:title,p_category:category,p_excerpt:excerpt,p_content:content,p_image_url:image_url,p_published:true});if(!r.ok)throw new Error('Could not publish blog post.');status.textContent='Blog post published.';form.reset();renderBlog();}catch(ex){status.textContent=ex.message||'Could not publish blog post.';}});}

  async function renderBlogComments(){
    const list=document.getElementById('admin-blog-comments'); if(!list||!api()?.ready)return;
    const c=adminCreds(); const r=await api().rpc('admin_blog_comments_list',{p_username:c.username||'',p_password:c.password||''});
    const items=r?.ok&&Array.isArray(r.data)?r.data:[];
    list.innerHTML=items.length?items.map(x=>`<article class="admin-item"><div class="admin-item-main"><strong>${esc(x.post_slug)}</strong><small>${esc(x.name)} · ${new Date(x.created_at).toLocaleString('en-NG')}</small><p>${esc(x.comment)}</p>${x.admin_reply?`<div class="admin-reply"><strong>Your reply</strong><p>${esc(x.admin_reply)}</p></div>`:''}</div><div class="admin-item-actions"><button class="btn btn-ghost-light reply-comment" data-id="${esc(x.id)}">${x.admin_reply?'Edit Reply':'Reply'}</button><button class="btn btn-ghost-light delete-comment" data-id="${esc(x.id)}">Delete</button></div></article>`).join(''):'<p class="admin-card-note">No public comments yet.</p>';
    list.querySelectorAll('.reply-comment').forEach(b=>b.onclick=async()=>{
      const reply=prompt('Reply to this comment:',items.find(x=>x.id===b.dataset.id)?.admin_reply||''); if(reply===null)return;
      const q=await api().rpc('admin_blog_comment_reply',{p_username:c.username||'',p_password:c.password||'',p_id:b.dataset.id,p_reply:reply.trim()});
      if(!q.ok)alert('Could not save reply.'); else renderBlogComments();
    });
    list.querySelectorAll('.delete-comment').forEach(b=>b.onclick=async()=>{
      if(!confirm('Delete this public comment?'))return;
      const q=await api().rpc('admin_blog_comment_delete',{p_username:c.username||'',p_password:c.password||'',p_id:b.dataset.id});
      if(!q.ok)alert('Could not delete comment.'); else renderBlogComments();
    });
  }
  async function loadSiteSettingsForm(){
    const form=document.getElementById('site-settings-form'); if(!form||!api()?.ready)return;
    const c=adminCreds(); const r=await api().rpc('admin_site_settings_get',{p_username:c.username||'',p_password:c.password||''});
    if(r?.ok&&Array.isArray(r.data)&&r.data[0]){const x=r.data[0];['phone','whatsapp','email','instagram','facebook','youtube','tiktok','x'].forEach(k=>{if(form.elements[k])form.elements[k].value=x[k]||'';});}
  }
  function bindSiteSettings(){
    const form=document.getElementById('site-settings-form'); if(!form||form.dataset.bound)return; form.dataset.bound='1';
    form.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(form),c=adminCreds(),status=document.getElementById('site-settings-status');try{
      const payload={phone:String(f.get('phone')||'').trim(),whatsapp:String(f.get('whatsapp')||'').trim(),email:String(f.get('email')||'').trim(),instagram:String(f.get('instagram')||'').trim(),facebook:String(f.get('facebook')||'').trim(),youtube:String(f.get('youtube')||'').trim(),tiktok:String(f.get('tiktok')||'').trim(),x:String(f.get('x')||'').trim()};
      const r=await api().rpc('admin_site_settings_update',{p_username:c.username||'',p_password:c.password||'',p_phone:payload.phone,p_whatsapp:payload.whatsapp,p_email:payload.email,p_instagram:payload.instagram,p_facebook:payload.facebook,p_youtube:payload.youtube,p_tiktok:payload.tiktok,p_x:payload.x});
      if(!r.ok)throw new Error('Could not save site settings.'); status.textContent='Saved. Public links will use these values.';
      window.MBSiteSettings={...window.MBSiteSettings,...payload}; window.MBSiteSettingsAPI?.apply(window.MBSiteSettings);
    }catch(ex){status.textContent=ex.message||'Could not save site settings.';}
    });
    loadSiteSettingsForm();
  }

  function bindForms(){document.getElementById('add-car-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{await window.MBStore.addCar({brand:String(f.get('brand')||'Mercedes-Benz'),name:String(f.get('name')).trim(),year:Number(f.get('year')),priceNGN:Number(f.get('priceNGN')),mileageKm:Number(f.get('mileageKm')),specTag:String(f.get('specTag')).trim(),image:String(f.get('image')).trim(),description:String(f.get('description')).trim(),status:String(f.get('status'))});e.currentTarget.reset();await renderCars();}catch(ex){alert(ex.message);}finally{btn.disabled=false;}});
    document.getElementById('add-before-after-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),types=f.getAll('galleryType[]'),vals=f.getAll('galleryUrl[]'),gallery=vals.map((v,i)=>({url:String(v).trim(),type:String(types[i]||'process')})).filter(x=>x.url),before=gallery.find(x=>x.type==='before')?.url,after=[...gallery].reverse().find(x=>x.type==='after')?.url;if(!before||!after){alert('Add at least one Before and one After image.');return;}const payload={title:String(f.get('title')).trim(),description:String(f.get('description')).trim(),before,after,video:String(f.get('video')||'').trim(),gallery};try{if(!api()?.ready)throw new Error('Supabase is not configured. Shared repair stories cannot be published until it is connected.');if(api()?.ready){const r=await api().post('before_after',{title:payload.title,description:payload.description,before_url:before,after_url:after,video_url:payload.video||null,gallery,active:true});if(!r.ok)throw new Error('Could not publish repair story to Supabase.');}window.MBData.addBeforeAfter(payload);e.currentTarget.reset();document.getElementById('repair-gallery-fields').innerHTML='<div class="gallery-input-row"><select name="galleryType[]"><option value="before">Before</option><option value="process">Process</option><option value="after">After</option></select><input name="galleryUrl[]" type="url" required placeholder="https://res.cloudinary.com/..."><button type="button" class="gallery-remove" aria-label="Remove image">×</button></div><div class="gallery-input-row"><select name="galleryType[]"><option value="before">Before</option><option value="process">Process</option><option value="after" selected>After</option></select><input name="galleryUrl[]" type="url" required placeholder="https://res.cloudinary.com/..."><button type="button" class="gallery-remove" aria-label="Remove image">×</button></div>';renderBeforeAfter();}catch(ex){alert(ex.message);}});
    document.getElementById('add-credential-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={title:String(f.get('title')).trim(),issuer:String(f.get('issuer')).trim(),year:String(f.get('year')||'').trim(),image:String(f.get('image')).trim(),description:String(f.get('description')||'').trim()};try{if(!api()?.ready)throw new Error('Supabase is not configured. Shared credentials cannot be published until it is connected.');if(api()?.ready){const r=await api().post('credentials',{title:payload.title,issuer:payload.issuer||null,year:payload.year?Number(payload.year):null,image_url:payload.image,description:payload.description,active:true});if(!r.ok)throw new Error('Could not publish credential.');}window.MBData.addCredential(payload);e.currentTarget.reset();renderCredentials();}catch(ex){alert(ex.message);}});
    document.getElementById('add-gallery-image')?.addEventListener('click',()=>{const root=document.getElementById('repair-gallery-fields');const row=document.createElement('div');row.className='gallery-input-row';row.innerHTML='<select name="galleryType[]"><option value="process">Process</option><option value="before">Before</option><option value="after">After</option></select><input name="galleryUrl[]" type="url" required placeholder="https://res.cloudinary.com/..." aria-label="Image URL"><button type="button" class="gallery-remove" aria-label="Remove image">×</button>';root.appendChild(row);});
    document.addEventListener('click',e=>{const b=e.target.closest('.gallery-remove');if(!b)return;const rows=[...document.querySelectorAll('#repair-gallery-fields .gallery-input-row')];if(rows.length>2)b.closest('.gallery-input-row').remove();else b.previousElementSibling.value='';});
    document.getElementById('btn-cloudinary')?.addEventListener('click',()=>window.MBCloudinary?.openUploader?.());
    document.getElementById('admin-logout')?.addEventListener('click',()=>{sessionStorage.removeItem('mbac_admin_session');location.replace('/mbac-control-7x4k9');});
    document.getElementById('migrate-legacy-data')?.addEventListener('click',async()=>{const status=document.getElementById('migration-status');try{status.textContent='Migrating…';const n=await window.MBData.migrateLegacyLocalData();status.textContent=`Migration complete: ${n} records sent to Supabase.`;await renderCars();await renderBeforeAfter();}catch(ex){status.textContent=ex.message||'Migration failed.';}});
  }
  async function boot(){if(!(await ensure()))return;document.querySelector('.site-header')?.style.removeProperty('visibility');document.getElementById('page-content')?.style.removeProperty('visibility');sectionNav();bindTimeModal();bindBlog();bindSiteSettings();bindForms();await Promise.allSettled([window.MBData?.hydrate?.(true),window.MBStore?.hydrate?.()]);await Promise.allSettled([renderCars(),renderAppointments(),renderBeforeAfter(),renderCredentials(),renderBlog(),renderBlogComments(),loadSiteSettingsForm()]);}
  document.addEventListener('DOMContentLoaded',boot);
})();
