/* Appointment queue + editable service/diagnostic selector. */
(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const wa='2348106958638';
  const formatDate=d=>new Intl.DateTimeFormat('en-NG',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${d}T00:00:00`));
  function renderOptions(){const s=document.querySelector('select[name="service"]');if(!s||!window.MBData)return;const current=new URLSearchParams(location.search).get('service')||s.value;const all=[...window.MBData.getServices(),...window.MBData.getDiagnostics().map(x=>x.name)];s.innerHTML='<option value="">Select a service or diagnostic</option>'+[...new Set(all)].map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(current)s.value=current;}
  function renderQueue(){const root=document.getElementById('appointment-queue');if(!root||!window.MBData)return;const today=new Date();today.setHours(0,0,0,0);const slots=window.MBData.getSlots().filter(s=>new Date(`${s.date}T00:00:00`)>=today&&s.status==='open'&&Number(s.booked)<Number(s.capacity)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).slice(0,8);if(!slots.length){root.innerHTML='<div class="queue-empty">No public slots are currently open. Send a WhatsApp request and the workshop will arrange the next available time.</div>';return;}root.innerHTML=slots.map((s,i)=>`<label class="queue-slot ${i===0?'is-next':''}"><input type="radio" name="slot" value="${esc(s.id)}" ${i===0?'checked':''} required><span class="queue-slot-main"><strong>${i===0?'NEXT AVAILABLE':'AVAILABLE'}</strong><b>${formatDate(s.date)}</b><span>${esc(s.time)} · ${Number(s.capacity)-Number(s.booked)} place${Number(s.capacity)-Number(s.booked)===1?'':'s'} left</span></span><span class="queue-slot-check">Select</span></label>`).join('');}
  function bind(){const form=document.getElementById('appointment-form');if(!form||form.dataset.bound)return;form.dataset.bound='1';renderOptions();renderQueue();const date=form.date;if(date){const now=new Date();date.min=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);}form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const slot=window.MBData.getSlots().find(x=>x.id===fd.get('slot'));if(!slot){alert('Please select an available appointment time.');return;}if(!window.MBData.bookSlot(slot.id)){alert('That appointment time has just been taken. Please select another time.');renderQueue();return;}const payload={name:String(fd.get('name')).trim(),phone:String(fd.get('phone')).trim(),model:String(fd.get('model')).trim(),year:String(fd.get('year')||''),service:String(fd.get('service')),date:slot.date,time:slot.time,slotId:slot.id,registration:String(fd.get('registration')||''),message:String(fd.get('message')).trim()};const a=window.MBData.addAppointment(payload);window.MBBackend?.post('appointments',{name:payload.name,phone:payload.phone,model:payload.model,year:payload.year?Number(payload.year):null,service:payload.service,registration:payload.registration||null,message:payload.message,status:'requested'}).catch(()=>{});const msg=[`Hello Moses Benz Auto Care. My appointment request is:`,`Reference: ${a.id}`,`Name: ${a.name}`,`Phone: ${a.phone}`,`Mercedes: ${a.model}${a.year?` (${a.year})`:''}`,`Service / Diagnostic: ${a.service}`,`Scheduled: ${formatDate(a.date)} at ${a.time}`,`Registration: ${a.registration||'Not supplied'}`,`Issue / request: ${a.message}`].join('\n');const status=document.getElementById('appointment-status');if(status)status.textContent='Appointment request saved. Opening WhatsApp so the workshop can confirm it.';window.open(`https://wa.me/${wa}?text=${encodeURIComponent(msg)}`,'_blank','noopener');form.reset();renderOptions();renderQueue();});}
  window.initAppointmentPage=bind;
})();
