/* Moses Benz Auto Care — GitHub-hosted Mercedes-Benz catalogue. Car data/images live in /cars; Supabase stores only visibility flags. */
window.MBCars = [
  {
    "id": "car-a-180-2021",
    "slug": "a-180-2021",
    "name": "A 180",
    "year": 2021,
    "priceNGN": 32000000,
    "mileageKm": 41000,
    "specTag": "1.3L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/a-180-2021/a-180-2021.jpg",
    "description": "Mercedes-Benz A-Class hatchback.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "a 180",
      "a class",
      "a-180",
      "a-class",
      "a180",
      "aclass",
      "benz a 180",
      "mercedes a 180"
    ]
  },
  {
    "id": "car-a-200-2022",
    "slug": "a-200-2022",
    "name": "A 200",
    "year": 2022,
    "priceNGN": 38000000,
    "mileageKm": 29000,
    "specTag": "1.3L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/a-200-2022/a-200-2022.jpg",
    "description": "A-Class. prepared for editing.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "a 200",
      "a class",
      "a-200",
      "a-class",
      "a200",
      "aclass",
      "benz a 200",
      "mercedes a 200"
    ]
  },
  {
    "id": "car-a-250-2023",
    "slug": "a-250-2023",
    "name": "A 250",
    "year": 2023,
    "priceNGN": 48000000,
    "mileageKm": 18000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/a-250-2023/a-250-2023.jpg",
    "description": "A-Class performance-oriented.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "a 250",
      "a class",
      "a-250",
      "a-class",
      "a250",
      "aclass",
      "benz a 250",
      "mercedes a 250"
    ]
  },
  {
    "id": "car-cla-200-2022",
    "slug": "cla-200-2022",
    "name": "CLA 200",
    "year": 2022,
    "priceNGN": 41000000,
    "mileageKm": 32000,
    "specTag": "1.3L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/cla-200-2022/cla-200-2022.jpg",
    "description": "CLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz cla 200",
      "cla 200",
      "cla class",
      "cla-200",
      "cla-class",
      "cla200",
      "claclass",
      "mercedes cla 200"
    ]
  },
  {
    "id": "car-cla-250-2023",
    "slug": "cla-250-2023",
    "name": "CLA 250",
    "year": 2023,
    "priceNGN": 52000000,
    "mileageKm": 21000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/cla-250-2023/cla-250-2023.jpg",
    "description": "CLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz cla 250",
      "cla 250",
      "cla class",
      "cla-250",
      "cla-class",
      "cla250",
      "claclass",
      "mercedes cla 250"
    ]
  },
  {
    "id": "car-cla-250-e-2024",
    "slug": "cla-250-e-2024",
    "name": "CLA 250 e",
    "year": 2024,
    "priceNGN": 59000000,
    "mileageKm": 12000,
    "specTag": "Plug-in Hybrid",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/cla-250-e-2024/cla-250-e-2024.jpg",
    "description": "CLA plug-in hybrid.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz cla 250 e",
      "cla 250 e",
      "cla class",
      "cla-250-e",
      "cla-class",
      "cla250e",
      "claclass",
      "mercedes cla 250 e"
    ]
  },
  {
    "id": "car-c-180-2020",
    "slug": "c-180-2020",
    "name": "C 180",
    "year": 2020,
    "priceNGN": 32000000,
    "mileageKm": 61000,
    "specTag": "1.5L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-180-2020/c-180-2020.jpg",
    "description": "C-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 180",
      "c 180",
      "c class",
      "c-180",
      "c-class",
      "c180",
      "cclass",
      "mercedes c 180"
    ]
  },
  {
    "id": "car-c-200-2021",
    "slug": "c-200-2021",
    "name": "C 200",
    "year": 2021,
    "priceNGN": 42000000,
    "mileageKm": 52000,
    "specTag": "1.5L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-200-2021/c-200-2021.jpg",
    "description": "C-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 200",
      "c 200",
      "c class",
      "c-200",
      "c-class",
      "c200",
      "cclass",
      "mercedes c 200"
    ]
  },
  {
    "id": "car-c-300-2022",
    "slug": "c-300-2022",
    "name": "C 300",
    "year": 2022,
    "priceNGN": 58500000,
    "mileageKm": 38200,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-300-2022/c-300-2022.jpg",
    "description": "C-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 300",
      "c 300",
      "c class",
      "c-300",
      "c-class",
      "c300",
      "cclass",
      "mercedes c 300"
    ]
  },
  {
    "id": "car-c-300-e-2022",
    "slug": "c-300-e-2022",
    "name": "C 300 e",
    "year": 2022,
    "priceNGN": 62000000,
    "mileageKm": 30000,
    "specTag": "Plug-in Hybrid",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-300-e-2022/c-300-e-2022.jpg",
    "description": "C-Class plug-in hybrid.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 300 e",
      "c 300 e",
      "c class",
      "c-300-e",
      "c-class",
      "c300e",
      "cclass",
      "mercedes c 300 e"
    ]
  },
  {
    "id": "car-c-43-amg-2022",
    "slug": "c-43-amg-2022",
    "name": "C 43 AMG",
    "year": 2022,
    "priceNGN": 82000000,
    "mileageKm": 26000,
    "specTag": "3.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-43-amg-2022/c-43-amg-2022.jpg",
    "description": "AMG C-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 43 amg",
      "c 43",
      "c 43 amg",
      "c class",
      "c-43-amg",
      "c-class",
      "c43",
      "c43amg",
      "cclass",
      "mercedes c 43 amg"
    ]
  },
  {
    "id": "car-c-63-s-amg-2021",
    "slug": "c-63-s-amg-2021",
    "name": "C 63 S AMG",
    "year": 2021,
    "priceNGN": 92000000,
    "mileageKm": 34500,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/c-63-s-amg-2021/c-63-s-amg-2021.jpg",
    "description": "AMG C-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz c 63 s amg",
      "c 63 s",
      "c 63 s amg",
      "c class",
      "c-63-s-amg",
      "c-class",
      "c63s",
      "c63samg",
      "cclass",
      "mercedes c 63 s amg"
    ]
  },
  {
    "id": "car-e-200-2020",
    "slug": "e-200-2020",
    "name": "E 200",
    "year": 2020,
    "priceNGN": 42000000,
    "mileageKm": 61000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-200-2020/e-200-2020.jpg",
    "description": "E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 200",
      "e 200",
      "e class",
      "e-200",
      "e-class",
      "e200",
      "eclass",
      "mercedes e 200"
    ]
  },
  {
    "id": "car-e-220d-2021",
    "slug": "e-220d-2021",
    "name": "E 220d",
    "year": 2021,
    "priceNGN": 48000000,
    "mileageKm": 55000,
    "specTag": "2.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-220d-2021/e-220d-2021.jpg",
    "description": "E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 220d",
      "e 220d",
      "e class",
      "e-220d",
      "e-class",
      "e220d",
      "eclass",
      "mercedes e 220d"
    ]
  },
  {
    "id": "car-e-300-2021",
    "slug": "e-300-2021",
    "name": "E 300",
    "year": 2021,
    "priceNGN": 52000000,
    "mileageKm": 48800,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-300-2021/e-300-2021.jpg",
    "description": "E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 300",
      "e 300",
      "e class",
      "e-300",
      "e-class",
      "e300",
      "eclass",
      "mercedes e 300"
    ]
  },
  {
    "id": "car-e-350-2022",
    "slug": "e-350-2022",
    "name": "E 350",
    "year": 2022,
    "priceNGN": 62000000,
    "mileageKm": 36000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-350-2022/e-350-2022.jpg",
    "description": "E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 350",
      "e 350",
      "e class",
      "e-350",
      "e-class",
      "e350",
      "eclass",
      "mercedes e 350"
    ]
  },
  {
    "id": "car-e-350e-2024",
    "slug": "e-350e-2024",
    "name": "E 350e",
    "year": 2024,
    "priceNGN": 76000000,
    "mileageKm": 15000,
    "specTag": "Plug-in Hybrid",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-350e-2024/e-350e-2024.jpg",
    "description": "E-Class plug-in hybrid.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 350e",
      "e 350e",
      "e class",
      "e-350e",
      "e-class",
      "e350e",
      "eclass",
      "mercedes e 350e"
    ]
  },
  {
    "id": "car-e-450-4matic-2022",
    "slug": "e-450-4matic-2022",
    "name": "E 450 4MATIC",
    "year": 2022,
    "priceNGN": 73500000,
    "mileageKm": 29400,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-450-4matic-2022/e-450-4matic-2022.jpg",
    "description": "E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 450 4matic",
      "e 450 4matic",
      "e class",
      "e-450-4matic",
      "e-class",
      "e4504matic",
      "eclass",
      "mercedes e 450 4matic"
    ]
  },
  {
    "id": "car-e-53-amg-2022",
    "slug": "e-53-amg-2022",
    "name": "E 53 AMG",
    "year": 2022,
    "priceNGN": 105000000,
    "mileageKm": 19000,
    "specTag": "3.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-53-amg-2022/e-53-amg-2022.jpg",
    "description": "AMG E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 53 amg",
      "e 53",
      "e 53 amg",
      "e class",
      "e-53-amg",
      "e-class",
      "e53",
      "e53amg",
      "eclass",
      "mercedes e 53 amg"
    ]
  },
  {
    "id": "car-e-63-s-amg-2021",
    "slug": "e-63-s-amg-2021",
    "name": "E 63 S AMG",
    "year": 2021,
    "priceNGN": 120000000,
    "mileageKm": 27000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/e-63-s-amg-2021/e-63-s-amg-2021.jpg",
    "description": "AMG E-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz e 63 s amg",
      "e 63 s",
      "e 63 s amg",
      "e class",
      "e-63-s-amg",
      "e-class",
      "e63s",
      "e63samg",
      "eclass",
      "mercedes e 63 s amg"
    ]
  },
  {
    "id": "car-s-450-2021",
    "slug": "s-450-2021",
    "name": "S 450",
    "year": 2021,
    "priceNGN": 118000000,
    "mileageKm": 36500,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/s-450-2021/s-450-2021.jpg",
    "description": "S-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz s 450",
      "mercedes s 450",
      "s 450",
      "s class",
      "s-450",
      "s-class",
      "s450",
      "sclass"
    ]
  },
  {
    "id": "car-s-500-2022",
    "slug": "s-500-2022",
    "name": "S 500",
    "year": 2022,
    "priceNGN": 155000000,
    "mileageKm": 21400,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/s-500-2022/s-500-2022.jpg",
    "description": "S-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz s 500",
      "mercedes s 500",
      "s 500",
      "s class",
      "s-500",
      "s-class",
      "s500",
      "sclass"
    ]
  },
  {
    "id": "car-s-580-2022",
    "slug": "s-580-2022",
    "name": "S 580",
    "year": 2022,
    "priceNGN": 168000000,
    "mileageKm": 21400,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/s-580-2022/s-580-2022.jpg",
    "description": "S-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz s 580",
      "mercedes s 580",
      "s 580",
      "s class",
      "s-580",
      "s-class",
      "s580",
      "sclass"
    ]
  },
  {
    "id": "car-maybach-s-580-2022",
    "slug": "maybach-s-580-2022",
    "name": "Maybach S 580",
    "year": 2022,
    "priceNGN": 220000000,
    "mileageKm": 12000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/maybach-s-580-2022/maybach-s-580-2022.jpg",
    "description": "Mercedes-Maybach.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz maybach s 580",
      "maybach class",
      "maybach s 580",
      "maybach-class",
      "maybach-s 580",
      "maybach-s-580",
      "maybachclass",
      "maybachs580",
      "mercedes maybach s 580"
    ]
  },
  {
    "id": "car-maybach-s-680-2023",
    "slug": "maybach-s-680-2023",
    "name": "Maybach S 680",
    "year": 2023,
    "priceNGN": 330000000,
    "mileageKm": 8000,
    "specTag": "6.0L V12",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/maybach-s-680-2023/maybach-s-680-2023.jpg",
    "description": "Mercedes-Maybach.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz maybach s 680",
      "maybach class",
      "maybach s 680",
      "maybach-class",
      "maybach-s 680",
      "maybach-s-680",
      "maybachclass",
      "maybachs680",
      "mercedes maybach s 680"
    ]
  },
  {
    "id": "car-gla-200-2024",
    "slug": "gla-200-2024",
    "name": "GLA 200",
    "year": 2024,
    "priceNGN": 52000000,
    "mileageKm": 12000,
    "specTag": "1.3L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gla-200-2024/gla-200-2024.jpg",
    "description": "GLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gla 200",
      "gla 200",
      "gla class",
      "gla-200",
      "gla-class",
      "gla200",
      "glaclass",
      "mercedes gla 200"
    ]
  },
  {
    "id": "car-gla-250-2022",
    "slug": "gla-250-2022",
    "name": "GLA 250",
    "year": 2022,
    "priceNGN": 58000000,
    "mileageKm": 24000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gla-250-2022/gla-250-2022.jpg",
    "description": "GLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gla 250",
      "gla 250",
      "gla class",
      "gla-250",
      "gla-class",
      "gla250",
      "glaclass",
      "mercedes gla 250"
    ]
  },
  {
    "id": "car-gla-250-e-2023",
    "slug": "gla-250-e-2023",
    "name": "GLA 250 e",
    "year": 2023,
    "priceNGN": 65000000,
    "mileageKm": 18000,
    "specTag": "Plug-in Hybrid",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gla-250-e-2023/gla-250-e-2023.jpg",
    "description": "GLA plug-in hybrid.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gla 250 e",
      "gla 250 e",
      "gla class",
      "gla-250-e",
      "gla-class",
      "gla250e",
      "glaclass",
      "mercedes gla 250 e"
    ]
  },
  {
    "id": "car-gla-35-amg-2022",
    "slug": "gla-35-amg-2022",
    "name": "GLA 35 AMG",
    "year": 2022,
    "priceNGN": 78000000,
    "mileageKm": 21000,
    "specTag": "2.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gla-35-amg-2022/gla-35-amg-2022.jpg",
    "description": "AMG GLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gla 35 amg",
      "gla 35",
      "gla 35 amg",
      "gla class",
      "gla-35-amg",
      "gla-class",
      "gla35",
      "gla35amg",
      "glaclass",
      "mercedes gla 35 amg"
    ]
  },
  {
    "id": "car-gla-45-amg-2023",
    "slug": "gla-45-amg-2023",
    "name": "GLA 45 AMG",
    "year": 2023,
    "priceNGN": 95000000,
    "mileageKm": 14000,
    "specTag": "2.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gla-45-amg-2023/gla-45-amg-2023.jpg",
    "description": "AMG GLA.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gla 45 amg",
      "gla 45",
      "gla 45 amg",
      "gla class",
      "gla-45-amg",
      "gla-class",
      "gla45",
      "gla45amg",
      "glaclass",
      "mercedes gla 45 amg"
    ]
  },
  {
    "id": "car-glb-200-2022",
    "slug": "glb-200-2022",
    "name": "GLB 200",
    "year": 2022,
    "priceNGN": 48000000,
    "mileageKm": 32000,
    "specTag": "1.3L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glb-200-2022/glb-200-2022.jpg",
    "description": "GLB.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glb 200",
      "glb 200",
      "glb class",
      "glb-200",
      "glb-class",
      "glb200",
      "glbclass",
      "mercedes glb 200"
    ]
  },
  {
    "id": "car-glb-200d-2022",
    "slug": "glb-200d-2022",
    "name": "GLB 200d",
    "year": 2022,
    "priceNGN": 50000000,
    "mileageKm": 37000,
    "specTag": "2.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glb-200d-2022/glb-200d-2022.jpg",
    "description": "GLB.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glb 200d",
      "glb 200d",
      "glb class",
      "glb-200d",
      "glb-class",
      "glb200d",
      "glbclass",
      "mercedes glb 200d"
    ]
  },
  {
    "id": "car-glb-250-2022",
    "slug": "glb-250-2022",
    "name": "GLB 250",
    "year": 2022,
    "priceNGN": 56000000,
    "mileageKm": 26000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glb-250-2022/glb-250-2022.jpg",
    "description": "GLB.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glb 250",
      "glb 250",
      "glb class",
      "glb-250",
      "glb-class",
      "glb250",
      "glbclass",
      "mercedes glb 250"
    ]
  },
  {
    "id": "car-glb-35-amg-2022",
    "slug": "glb-35-amg-2022",
    "name": "GLB 35 AMG",
    "year": 2022,
    "priceNGN": 78000000,
    "mileageKm": 22000,
    "specTag": "2.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glb-35-amg-2022/glb-35-amg-2022.jpg",
    "description": "AMG GLB.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glb 35 amg",
      "glb 35",
      "glb 35 amg",
      "glb class",
      "glb-35-amg",
      "glb-class",
      "glb35",
      "glb35amg",
      "glbclass",
      "mercedes glb 35 amg"
    ]
  },
  {
    "id": "car-glc-300-2022",
    "slug": "glc-300-2022",
    "name": "GLC 300",
    "year": 2022,
    "priceNGN": 64500000,
    "mileageKm": 41100,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glc-300-2022/glc-300-2022.jpg",
    "description": "GLC.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glc 300",
      "glc 300",
      "glc class",
      "glc-300",
      "glc-class",
      "glc300",
      "glcclass",
      "mercedes glc 300"
    ]
  },
  {
    "id": "car-glc-300-coupe-2023",
    "slug": "glc-300-coupe-2023",
    "name": "GLC 300 Coupe",
    "year": 2023,
    "priceNGN": 75000000,
    "mileageKm": 21000,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glc-300-coupe-2023/glc-300-coupe-2023.jpg",
    "description": "GLC Coupé.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glc 300 coupe",
      "glc 300 coupe",
      "glc class",
      "glc-300-coupe",
      "glc-class",
      "glc300coupe",
      "glcclass",
      "mercedes glc 300 coupe"
    ]
  },
  {
    "id": "car-glc-43-amg-2022",
    "slug": "glc-43-amg-2022",
    "name": "GLC 43 AMG",
    "year": 2022,
    "priceNGN": 88000000,
    "mileageKm": 24000,
    "specTag": "3.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glc-43-amg-2022/glc-43-amg-2022.jpg",
    "description": "AMG GLC.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glc 43 amg",
      "glc 43",
      "glc 43 amg",
      "glc class",
      "glc-43-amg",
      "glc-class",
      "glc43",
      "glc43amg",
      "glcclass",
      "mercedes glc 43 amg"
    ]
  },
  {
    "id": "car-glc-63-s-amg-2022",
    "slug": "glc-63-s-amg-2022",
    "name": "GLC 63 S AMG",
    "year": 2022,
    "priceNGN": 125000000,
    "mileageKm": 18000,
    "specTag": "4.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/glc-63-s-amg-2022/glc-63-s-amg-2022.jpg",
    "description": "AMG GLC.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz glc 63 s amg",
      "glc 63 s",
      "glc 63 s amg",
      "glc class",
      "glc-63-s-amg",
      "glc-class",
      "glc63s",
      "glc63samg",
      "glcclass",
      "mercedes glc 63 s amg"
    ]
  },
  {
    "id": "car-gle-350-2020",
    "slug": "gle-350-2020",
    "name": "GLE 350",
    "year": 2020,
    "priceNGN": 58500000,
    "mileageKm": 58200,
    "specTag": "2.0L Turbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gle-350-2020/gle-350-2020.jpg",
    "description": "GLE.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gle 350",
      "gle 350",
      "gle class",
      "gle-350",
      "gle-class",
      "gle350",
      "gleclass",
      "mercedes gle 350"
    ]
  },
  {
    "id": "car-gle-450-2021",
    "slug": "gle-450-2021",
    "name": "GLE 450",
    "year": 2021,
    "priceNGN": 68000000,
    "mileageKm": 45300,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gle-450-2021/gle-450-2021.jpg",
    "description": "GLE.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gle 450",
      "gle 450",
      "gle class",
      "gle-450",
      "gle-class",
      "gle450",
      "gleclass",
      "mercedes gle 450"
    ]
  },
  {
    "id": "car-gle-450-coupe-2022",
    "slug": "gle-450-coupe-2022",
    "name": "GLE 450 Coupe",
    "year": 2022,
    "priceNGN": 90000000,
    "mileageKm": 29000,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gle-450-coupe-2022/gle-450-coupe-2022.jpg",
    "description": "GLE Coupé.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gle 450 coupe",
      "gle 450 coupe",
      "gle class",
      "gle-450-coupe",
      "gle-class",
      "gle450coupe",
      "gleclass",
      "mercedes gle 450 coupe"
    ]
  },
  {
    "id": "car-gle-53-amg-2022",
    "slug": "gle-53-amg-2022",
    "name": "GLE 53 AMG",
    "year": 2022,
    "priceNGN": 98000000,
    "mileageKm": 27600,
    "specTag": "3.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gle-53-amg-2022/gle-53-amg-2022.jpg",
    "description": "AMG GLE.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gle 53 amg",
      "gle 53",
      "gle 53 amg",
      "gle class",
      "gle-53-amg",
      "gle-class",
      "gle53",
      "gle53amg",
      "gleclass",
      "mercedes gle 53 amg"
    ]
  },
  {
    "id": "car-gle-63-s-amg-2021",
    "slug": "gle-63-s-amg-2021",
    "name": "GLE 63 S AMG",
    "year": 2021,
    "priceNGN": 145000000,
    "mileageKm": 22000,
    "specTag": "4.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gle-63-s-amg-2021/gle-63-s-amg-2021.jpg",
    "description": "AMG GLE.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gle 63 s amg",
      "gle 63 s",
      "gle 63 s amg",
      "gle class",
      "gle-63-s-amg",
      "gle-class",
      "gle63s",
      "gle63samg",
      "gleclass",
      "mercedes gle 63 s amg"
    ]
  },
  {
    "id": "car-gls-450-2021",
    "slug": "gls-450-2021",
    "name": "GLS 450",
    "year": 2021,
    "priceNGN": 92000000,
    "mileageKm": 49700,
    "specTag": "3.0L Turbo I6",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gls-450-2021/gls-450-2021.jpg",
    "description": "GLS.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gls 450",
      "gls 450",
      "gls class",
      "gls-450",
      "gls-class",
      "gls450",
      "glsclass",
      "mercedes gls 450"
    ]
  },
  {
    "id": "car-gls-580-2022",
    "slug": "gls-580-2022",
    "name": "GLS 580",
    "year": 2022,
    "priceNGN": 139000000,
    "mileageKm": 31200,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gls-580-2022/gls-580-2022.jpg",
    "description": "GLS.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gls 580",
      "gls 580",
      "gls class",
      "gls-580",
      "gls-class",
      "gls580",
      "glsclass",
      "mercedes gls 580"
    ]
  },
  {
    "id": "car-gls-63-amg-2021",
    "slug": "gls-63-amg-2021",
    "name": "GLS 63 AMG",
    "year": 2021,
    "priceNGN": 155000000,
    "mileageKm": 24000,
    "specTag": "4.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/gls-63-amg-2021/gls-63-amg-2021.jpg",
    "description": "AMG GLS.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz gls 63 amg",
      "gls 63",
      "gls 63 amg",
      "gls class",
      "gls-63-amg",
      "gls-class",
      "gls63",
      "gls63amg",
      "glsclass",
      "mercedes gls 63 amg"
    ]
  },
  {
    "id": "car-maybach-gls-600-2022",
    "slug": "maybach-gls-600-2022",
    "name": "Maybach GLS 600",
    "year": 2022,
    "priceNGN": 220000000,
    "mileageKm": 16000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/maybach-gls-600-2022/maybach-gls-600-2022.jpg",
    "description": "Mercedes-Maybach GLS.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz maybach gls 600",
      "maybach class",
      "maybach gls 600",
      "maybach-class",
      "maybach-gls 600",
      "maybach-gls-600",
      "maybachclass",
      "maybachgls600",
      "mercedes maybach gls 600"
    ]
  },
  {
    "id": "car-g-400d-2021",
    "slug": "g-400d-2021",
    "name": "G 400d",
    "year": 2021,
    "priceNGN": 150000000,
    "mileageKm": 31000,
    "specTag": "3.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/g-400d-2021/g-400d-2021.jpg",
    "description": "G-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz g 400d",
      "g 400d",
      "g class",
      "g-400d",
      "g-class",
      "g400d",
      "gclass",
      "mercedes g 400d"
    ]
  },
  {
    "id": "car-g-500-2021",
    "slug": "g-500-2021",
    "name": "G 500",
    "year": 2021,
    "priceNGN": 165000000,
    "mileageKm": 25000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/g-500-2021/g-500-2021.jpg",
    "description": "G-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz g 500",
      "g 500",
      "g class",
      "g-500",
      "g-class",
      "g500",
      "gclass",
      "mercedes g 500"
    ]
  },
  {
    "id": "car-g-550-2020",
    "slug": "g-550-2020",
    "name": "G 550",
    "year": 2020,
    "priceNGN": 135000000,
    "mileageKm": 38000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/g-550-2020/g-550-2020.jpg",
    "description": "G-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz g 550",
      "g 550",
      "g class",
      "g-550",
      "g-class",
      "g550",
      "gclass",
      "mercedes g 550"
    ]
  },
  {
    "id": "car-g-63-amg-2023",
    "slug": "g-63-amg-2023",
    "name": "G 63 AMG",
    "year": 2023,
    "priceNGN": 185000000,
    "mileageKm": 8200,
    "specTag": "4.0L V8 Biturbo",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/g-63-amg-2023/g-63-amg-2023.jpg",
    "description": "AMG G-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz g 63 amg",
      "g 63",
      "g 63 amg",
      "g class",
      "g-63-amg",
      "g-class",
      "g63",
      "g63amg",
      "gclass",
      "mercedes g 63 amg"
    ]
  },
  {
    "id": "car-g-450d-2024",
    "slug": "g-450d-2024",
    "name": "G 450d",
    "year": 2024,
    "priceNGN": 175000000,
    "mileageKm": 9000,
    "specTag": "3.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/g-450d-2024/g-450d-2024.jpg",
    "description": "G-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz g 450d",
      "g 450d",
      "g class",
      "g-450d",
      "g-class",
      "g450d",
      "gclass",
      "mercedes g 450d"
    ]
  },
  {
    "id": "car-v-220d-2020",
    "slug": "v-220d-2020",
    "name": "V 220d",
    "year": 2020,
    "priceNGN": 55000000,
    "mileageKm": 61000,
    "specTag": "2.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/v-220d-2020/v-220d-2020.jpg",
    "description": "V-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz v 220d",
      "mercedes v 220d",
      "v 220d",
      "v class",
      "v-220d",
      "v-class",
      "v220d",
      "vclass"
    ]
  },
  {
    "id": "car-v-250d-2021",
    "slug": "v-250d-2021",
    "name": "V 250d",
    "year": 2021,
    "priceNGN": 65000000,
    "mileageKm": 48000,
    "specTag": "2.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/v-250d-2021/v-250d-2021.jpg",
    "description": "V-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz v 250d",
      "mercedes v 250d",
      "v 250d",
      "v class",
      "v-250d",
      "v-class",
      "v250d",
      "vclass"
    ]
  },
  {
    "id": "car-v-300d-2022",
    "slug": "v-300d-2022",
    "name": "V 300d",
    "year": 2022,
    "priceNGN": 78000000,
    "mileageKm": 32000,
    "specTag": "2.0L Diesel",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/v-300d-2022/v-300d-2022.jpg",
    "description": "V-Class.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz v 300d",
      "mercedes v 300d",
      "v 300d",
      "v class",
      "v-300d",
      "v-class",
      "v300d",
      "vclass"
    ]
  },
  {
    "id": "car-sl-43-amg-2023",
    "slug": "sl-43-amg-2023",
    "name": "SL 43 AMG",
    "year": 2023,
    "priceNGN": 120000000,
    "mileageKm": 12000,
    "specTag": "2.0L AMG",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/sl-43-amg-2023/sl-43-amg-2023.jpg",
    "description": "SL Roadster.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz sl 43 amg",
      "mercedes sl 43 amg",
      "sl 43",
      "sl 43 amg",
      "sl class",
      "sl-43-amg",
      "sl-class",
      "sl43",
      "sl43amg",
      "slclass"
    ]
  },
  {
    "id": "car-sl-55-amg-2022",
    "slug": "sl-55-amg-2022",
    "name": "SL 55 AMG",
    "year": 2022,
    "priceNGN": 145000000,
    "mileageKm": 14000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/sl-55-amg-2022/sl-55-amg-2022.jpg",
    "description": "SL Roadster.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "benz sl 55 amg",
      "mercedes sl 55 amg",
      "sl 55",
      "sl 55 amg",
      "sl class",
      "sl-55-amg",
      "sl-class",
      "sl55",
      "sl55amg",
      "slclass"
    ]
  },
  {
    "id": "car-amg-gt-55-2024",
    "slug": "amg-gt-55-2024",
    "name": "AMG GT 55",
    "year": 2024,
    "priceNGN": 175000000,
    "mileageKm": 7000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/amg-gt-55-2024/amg-gt-55-2024.jpg",
    "description": "Mercedes-AMG GT.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "amg class",
      "amg gt 55",
      "amg-class",
      "amg-gt-55",
      "amgclass",
      "amggt55",
      "benz amg gt 55",
      "gt 55",
      "gt55",
      "mercedes amg gt 55"
    ]
  },
  {
    "id": "car-amg-gt-63-2024",
    "slug": "amg-gt-63-2024",
    "name": "AMG GT 63",
    "year": 2024,
    "priceNGN": 210000000,
    "mileageKm": 6000,
    "specTag": "4.0L V8",
    "status": "available",
    "brand": "Mercedes-Benz",
    "image": "/cars/amg-gt-63-2024/amg-gt-63-2024.jpg",
    "description": "Mercedes-AMG GT.",
    "condition": "",
    "fuel": "",
    "transmission": "",
    "body": "",
    "drivetrain": "",
    "engineSize": "",
    "cylinders": "",
    "horsepower": "",
    "color": "",
    "interiorColor": "",
    "seats": "",
    "registered": "",
    "searchAliases": [
      "amg class",
      "amg gt 63",
      "amg-class",
      "amg-gt-63",
      "amgclass",
      "amggt63",
      "benz amg gt 63",
      "gt 63",
      "gt63",
      "mercedes amg gt 63"
    ]
  }
];
