(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const imageUrl=url=>{const u=String(url||'');if(!u)return '';if(!/res\.cloudinary\.com\//i.test(u)||!/\/image\/upload\//i.test(u))return u;if(/\/upload\/[^/]*\b(f_auto|f_jpg|q_auto|w_\d+)/i.test(u))return u;return u.replace('/image/upload/','/image/upload/f_jpg,q_auto,w_1200/');};
  const normalizeGallery=x=>{
    if(Array.isArray(x.gallery)&&x.gallery.length) return x.gallery.filter(i=>i&&i.url).map(i=>({url:i.url,type:i.type||'process'}));
    const out=[]; if(x.before||x.before_url)out.push({url:x.before||x.before_url,type:'before'}); if(x.after||x.after_url)out.push({url:x.after||x.after_url,type:'after'}); return out;
  };
  function initBeforeAfter(){const root=document.getElementById('before-after-grid');if(!root||!window.MBData)return;const items=window.MBData.getBeforeAfter();root.innerHTML=items.length?items.map((x,i)=>{const gallery=normalizeGallery(x);return `<article class="before-after-card" data-carousel><div class="before-after-carousel"><button class="carousel-arrow prev" type="button" aria-label="Previous image">‹</button><div class="before-after-track">${gallery.map((g,j)=>`<figure class="before-after-slide${j===0?' is-active':''}" data-index="${j}"><img src="${esc(imageUrl(g.url))}" alt="${esc(g.type)}: ${esc(x.title)}" loading="${j<2?'eager':'lazy'}"><figcaption>${esc(g.type)}</figcaption></figure>`).join('')}</div><button class="carousel-arrow next" type="button" aria-label="Next image">›</button><div class="carousel-dots" aria-label="Gallery images">${gallery.map((g,j)=>`<button type="button" class="carousel-dot${j===0?' is-active':''}" data-to="${j}" aria-label="Show image ${j+1}"></button>`).join('')}</div></div><div class="before-after-copy"><span class="eyebrow">Repair Story</span><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p>${(x.video||x.video_url)?`<video class="before-after-video" controls preload="metadata" src="${esc(x.video||x.video_url)}"></video>`:''}</div></article>`;}).join(''):'<div class="media-empty"><p>Repair transformations will appear here as the workshop publishes them.</p></div>';
    root.querySelectorAll('[data-carousel]').forEach(initCarousel);
  }
  function initCarousel(card){const slides=[...card.querySelectorAll('.before-after-slide')];if(slides.length<2)return;const dots=[...card.querySelectorAll('.carousel-dot')];let index=0,timer=null,paused=false,startX=0;const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('is-active',i===index));dots.forEach((d,i)=>d.classList.toggle('is-active',i===index));};const next=()=>show(index+1);const prev=()=>show(index-1);const start=()=>{clearInterval(timer);timer=setInterval(()=>{if(!paused)next();},2000);};const pause=()=>{paused=true;clearInterval(timer);};const resume=()=>{paused=false;start();};card.querySelector('.prev').addEventListener('click',()=>{pause();prev();setTimeout(resume,1200);});card.querySelector('.next').addEventListener('click',()=>{pause();next();setTimeout(resume,1200);});dots.forEach(d=>d.addEventListener('click',()=>{pause();show(+d.dataset.to);setTimeout(resume,1200);}));card.addEventListener('mouseenter',pause);card.addEventListener('mouseleave',resume);card.addEventListener('focusin',pause);card.addEventListener('focusout',e=>{if(!card.contains(e.relatedTarget))resume();});card.addEventListener('touchstart',e=>{pause();startX=e.changedTouches[0].clientX;},{passive:true});card.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-startX;if(Math.abs(dx)>45)(dx<0?next:prev)();setTimeout(resume,1200);},{passive:true});start();}
  function credentialCard(x){return `<article class="credential-card"><a href="${esc(x.image||x.image_url)}" target="_blank" rel="noopener"><img src="${esc(imageUrl(x.image||x.image_url))}" alt="${esc(x.title)}" loading="lazy"></a><div class="credential-copy"><span class="eyebrow">Credential</span><h3>${esc(x.title)}</h3><p class="credential-meta">${esc(x.issuer||'')}${x.year?` · ${esc(x.year)}`:''}</p><p>${esc(x.description||'')}</p></div></article>`;}
  function initCredentials(){const root=document.getElementById('credentials-grid');if(!root||!window.MBData)return;const items=window.MBData.getCredentials();root.innerHTML=items.length?items.map(credentialCard).join(''):'<div class="media-empty"><p>Workshop approvals and certificates will appear here as they are published.</p></div>';}
  function initHomeCredentials(){const root=document.getElementById('home-credentials-strip');if(!root||!window.MBData)return;const items=window.MBData.getCredentials().slice(0,4);root.innerHTML=items.length?items.map(x=>`<a class="credential-brand-chip page-route" href="credentials.html"><span class="credential-brand-icon"><img src="${esc(imageUrl(x.image||x.image_url))}" alt=""></span><span><strong>${esc(x.title)}</strong><small>${esc(x.issuer||'Approved / certified')}</small></span></a>`).join(''):'<div class="credential-brand-empty">Credentials can be added from the Admin portal.</div>';}
  window.initBeforeAfter=initBeforeAfter;window.initCredentials=initCredentials;window.initHomeCredentials=initHomeCredentials;
  window.addEventListener('mb:data-hydrated',()=>{initBeforeAfter();initCredentials();initHomeCredentials();});
})();