/* Moses Benz Auto Care — shared editable catalogue + Supabase hydration. */
(() => {
  const KEYS={services:'mbac_services_v5',appointments:'mbac_appointments_v4',reviews:'mbac_reviews_v4',beforeAfter:'mbac_before_after_v2',credentials:'mbac_credentials_v1'};
  const SERVICES=["Oil & Filter Service","Engine Oil & Fluid Check","Benz Servicing","Brake Inspection","Brake Pad Replacement","Brake Disc / Rotor Replacement","Brake Fluid Flush","ABS / ESP / SBC Repair","Tyre Replacement","Wheel Balancing","Wheel Alignment","Battery Testing & Replacement","Alternator & Charging Repair","Starter Motor Repair","Battery Drain Diagnosis","Engine Repair","Engine Overhaul / Rebuild","Timing Chain Inspection & Repair","Timing Belt Service","Spark Plug Replacement","Ignition Coil Replacement","Fuel System Repair","Fuel Injector Service","Fuel Pump Repair","Cooling System Service","Radiator Repair / Replacement","Water Pump Replacement","Thermostat Replacement","Coolant Flush","Automatic Transmission Service","Transmission Fluid & Filter Service","Transmission Repair / Rebuild","Gearbox Mount Replacement","Driveshaft / Propeller Shaft Repair","Differential Service & Repair","Transfer Case Service","Clutch Service","AIRMATIC Diagnosis & Repair","Air Suspension Compressor Repair","Air Suspension Leak Repair","Shock Absorber Replacement","Control Arm / Bush Replacement","Steering System Repair","Power Steering Service","Wheel Bearing Replacement","Air Conditioning Service","AC Gas Recharge","AC Compressor Repair","Climate Control Repair","Electrical System Repair","Wiring & CAN-Bus Diagnosis","ECU Coding & Programming","Key / Immobiliser Diagnosis","Window / Central Lock Repair","Lighting & Headlamp Repair","Parking Sensor / Camera Repair","MBUX / Infotainment Repair","Software / Module Updates","Airbag / SRS Repair","AdBlue / Emissions System Repair","DPF / Exhaust System Repair","Turbocharger Repair","Hybrid / EV System Inspection","Pre-Purchase Inspection","Roadworthiness Inspection","Accident / Collision Repair","Paint & Panel Repair","Paint Correction & Polishing","Ceramic Coating","Interior Detailing","Exterior Detailing","Headlight Restoration","Windshield / Glass Replacement","Benz Diagnosing","Benz Diagnosing — Full Vehicle Scan","Benz Diagnosing — Engine Management","Benz Diagnosing — Transmission & Gearbox","Benz Diagnosing — ABS / ESP / SBC","Benz Diagnosing — AIRMATIC / Air Suspension","Benz Diagnosing — Electrical & Battery","Benz Diagnosing — CAN-Bus / Communication","Benz Diagnosing — Air Conditioning / Climate","Benz Diagnosing — MBUX / Infotainment","Benz Diagnosing — Airbag / SRS","Benz Diagnosing — AdBlue / Emissions","Benz Diagnosing — Starting / No-Start","Benz Diagnosing — Turbo / Boost System","Benz Diagnosing — Cooling System","Benz Diagnosing — Steering & Suspension","Benz Diagnosing — Hybrid / EV System","Benz Diagnosing — Pre-Purchase","Benz Diagnosing — Road Test","Other"];
  const read=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback;}};
  const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false;}};
  const clone=x=>JSON.parse(JSON.stringify(x));
  function getServices(){let x=read(KEYS.services,null);if(!Array.isArray(x)){x=SERVICES.slice();write(KEYS.services,x);return x;}const cleaned=x.filter(v=>v!=='Service A'&&v!=='Service B');const merged=[...cleaned];SERVICES.forEach(v=>{if(!merged.includes(v))merged.push(v);});if(merged.length!==x.length||merged.some((v,i)=>v!==x[i]))write(KEYS.services,merged);return merged;}
  function saveServices(x){write(KEYS.services,x);}
  function getAppointments(){return read(KEYS.appointments,[]);}
  function addAppointment(data){const list=getAppointments();const a={id:'apt-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),status:'requested',reviewRequested:false,...data};list.push(a);write(KEYS.appointments,list);return a;}
  function updateAppointment(id,patch){const list=getAppointments();const i=list.findIndex(x=>x.id===id);if(i<0)return false;list[i]={...list[i],...patch};return write(KEYS.appointments,list);}
  function getReviews(){return read(KEYS.reviews,[]);}
  function addReview(data){const x=getReviews();const r={id:'rev-'+Date.now().toString(36),createdAt:new Date().toISOString(),...data};x.unshift(r);write(KEYS.reviews,x);return r;}
  const makeId=(prefix)=>{try{return crypto.randomUUID()}catch{return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}};
  function getBeforeAfter(){return read(KEYS.beforeAfter,[]);}
  function addBeforeAfter(data){const x=getBeforeAfter();const r={id:makeId('ba'),createdAt:new Date().toISOString(),...data};x.unshift(r);write(KEYS.beforeAfter,x);return r;}
  function removeBeforeAfter(id){write(KEYS.beforeAfter,getBeforeAfter().filter(x=>x.id!==id));}
  function getCredentials(){return read(KEYS.credentials,[]);}
  function addCredential(data){const x=getCredentials();const r={id:makeId('cert'),createdAt:new Date().toISOString(),...data};x.unshift(r);write(KEYS.credentials,x);return r;}
  function removeCredential(id){write(KEYS.credentials,getCredentials().filter(x=>x.id!==id));}
  async function hydrate(){
    if(!window.MBBackend?.ready)return;
    try{
      const [ba,certs]=await Promise.all([window.MBBackend.get('before_after','select=*&active=eq.true&order=created_at.desc'),window.MBBackend.get('credentials','select=*&active=eq.true&order=created_at.desc')]);
      if(ba.ok&&Array.isArray(ba.data)&&ba.data.length)write(KEYS.beforeAfter,ba.data.map(x=>({id:x.id,title:x.title,description:x.description,before:x.before_url,after:x.after_url,video:x.video_url,gallery:Array.isArray(x.gallery)?x.gallery:[],createdAt:x.created_at})));
      if(certs.ok&&Array.isArray(certs.data)&&certs.data.length)write(KEYS.credentials,certs.data.map(x=>({id:x.id,title:x.title,issuer:x.issuer,description:x.description,image:x.image_url,year:x.year,createdAt:x.created_at})));
      window.dispatchEvent(new CustomEvent('mb:data-hydrated'));
    }catch(e){console.warn('Moses Benz data hydration skipped',e);}
  }
  window.MBData={getServices,saveServices,getAppointments,addAppointment,updateAppointment,getReviews,addReview,getBeforeAfter,addBeforeAfter,removeBeforeAfter,getCredentials,addCredential,removeCredential,hydrate,KEYS};
})();
