-- Simple MBAC admin setup. NO Supabase Auth.
-- Requires pgcrypto (available in Supabase).
create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon, authenticated;

create or replace function public.verify_admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare u public.admin_users;
begin
  select * into u
  from public.admin_users
  where username = trim(p_username) and active = true
  limit 1;

  if u.id is null or not (u.password_hash = crypt(p_password, u.password_hash)) then
    return jsonb_build_object('authenticated', false);
  end if;

  return jsonb_build_object('authenticated', true, 'username', u.username);
end;
$$;

revoke all on function public.verify_admin_login(text,text) from public;
grant execute on function public.verify_admin_login(text,text) to anon, authenticated;

-- Add an administrator. Replace values before running:
-- insert into public.admin_users(username,password_hash)
-- values ('YOUR_USERNAME', crypt('YOUR_PASSWORD', gen_salt('bf')));
