-- Moses Benz Auto Care: simple admin table, NO Supabase Auth.
-- The `password` column stores a one-way SHA-256 hash, not plaintext.
-- Run this SQL once in Supabase SQL Editor.

create extension if not exists pgcrypto;

drop table if exists public.admin_users cascade;

create table public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Browser clients must never be allowed to read the table directly.
-- Login is checked through the RPC below.
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.verify_admin_login(
  p_username text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  u public.admin_users;
begin
  select * into u
  from public.admin_users
  where username = trim(p_username)
    and active = true
  limit 1;

  if not found then
    return jsonb_build_object('ok', false);
  end if;

  if u.password = encode(digest(p_password, 'sha256'), 'hex') then
    return jsonb_build_object('ok', true, 'username', u.username);
  end if;

  return jsonb_build_object('ok', false);
end;
$$;

revoke all on function public.verify_admin_login(text, text) from public;
grant execute on function public.verify_admin_login(text, text) to anon, authenticated;

-- Create your admin password hash:
-- SELECT encode(digest('YOUR_PASSWORD_HERE', 'sha256'), 'hex');
--
-- Then insert the resulting hash:
-- INSERT INTO public.admin_users (username, password)
-- VALUES ('YOUR_USERNAME', 'PASTE_HASH_HERE');
